app/urls.py
from django.urls import path

from app.views import ProjectListView, IndexView, ProjectDetailView, \
    UserCreateView, UserLoginView, UserLogOutView, \
    ProjectCreateView, ProjectUpdateView, PersonalProjectListView, \
    random_project_name_view, AddFavoriteView, DownloadAudioFileView, \
    UserDetailView

urlpatterns = [
    path("", view=IndexView.as_view(), name="index-view"),
    path("login/", view=UserLoginView.as_view(), name="user-login"),
    path("logout/", view=UserLogOutView.as_view(), name="user-logout"),
    path("ideas/", view=ProjectListView.as_view(), name="ideas-list"),
    path("personal_ideas/", view=PersonalProjectListView.as_view(),
         name="personal-ideas-list"),
    path("new_user/", view=UserCreateView.as_view(), name="user-create"),
    path("ideas/<slug:slug>", view=ProjectDetailView.as_view(),
         name="ideas-detail"),
    path("ideas/create/", view=ProjectCreateView.as_view(),
         name="ideas-create"),
    path("ideas/update/<slug:slug>", view=ProjectUpdateView.as_view(),
         name="ideas-update"),
    path("ideas/favorite/<slug:slug>", view=AddFavoriteView.as_view(),
         name="ideas-favorite"),
    path("random_project_name/", view=random_project_name_view,
         name="random-project-name"),
    path("download_audio/<slug:slug>", view=DownloadAudioFileView.as_view(),
         name="download-audio-file"),
    path("user/<int:pk>", view=UserDetailView.as_view(), name="user-detail"),
]

music_ideas/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from app.enums import VALID_AUDIO_FILE_TYPES, ProjectFileTypeChoices, \
    ProjectKeyChoices
from app.managers import CustomUserManager


class MidUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True, db_index=True)
    username = models.CharField(error_messages={
        'unique': _('A user with that username already exists.')},
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        max_length=20, unique=True,
        validators=[UnicodeUsernameValidator()],
        verbose_name='username',
        db_index=True)
    picture = models.FileField(upload_to="profile_pics/", null=True)
    description = models.TextField(blank=True, null=True)
    REQUIRED_FIELDS = ["email"]

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Project(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=6, unique=True, blank=True,
                            db_index=True)
    creator = models.ForeignKey(MidUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(blank=True, null=True)
    modified_at = models.DateTimeField(blank=True, null=True)
    is_private = models.BooleanField(default=False)
    tempo = models.IntegerField(max_length=3, blank=True, null=True)
    key = models.CharField(choices=ProjectKeyChoices.choices, blank=True,
                           null=True, max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
            self.slug = self.generate_slug()
        self.modified_at = timezone.now()
        return super(Project, self).save(*args, **kwargs)

    @staticmethod
    def generate_slug():
        generated_slug = None
        existing_slug = True
        while existing_slug:
            generated_slug = uuid.uuid4().hex[:6].upper()
            project_instance = Project.objects.filter(slug=generated_slug)
            if not project_instance.exists():
                existing_slug = False
        return generated_slug

    @property
    def joined_files(self):
        file_types = {
            ProjectFileTypeChoices.AUDIO_FILE.name: False,
            ProjectFileTypeChoices.MUSIC_SHEET.name: False,
            ProjectFileTypeChoices.ABLETON_PROJECT_FILE.name: False
        }
        for file in self.files.all():
            file_types[file.project_file_type] = file
        return file_types

    @property
    def favorite_count(self):
        return self.favorites.count()


class ProjectFile(models.Model):
    name = models.CharField(max_length=60)
    file = models.FileField(upload_to="media/")
    uploaded_at = models.DateTimeField(blank=True, null=True)
    project_file_type = models.CharField(max_length=255,
                                         choices=ProjectFileTypeChoices.choices)
    project = models.ForeignKey(Project, on_delete=models.CASCADE,
                                related_name="files")
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{} - {}".format(self.name, self.project_file_type)

    def clean(self):
        super(ProjectFile, self).clean()
        if self.project_file_type == ProjectFileTypeChoices.AUDIO_FILE.name:
            if not self.is_valid_audio_file(self.file):
                raise ValidationError("Not a valid file type")
        if self.project_file_type != \
                ProjectFileTypeChoices.ABLETON_PROJECT_FILE.name and \
                self.notes:
            raise ValidationError(
                "You can set the field 'notes' only with a project file")

    @staticmethod
    def is_valid_audio_file(file):
        for file_type, mime_type in VALID_AUDIO_FILE_TYPES.items():
            try:
                if file._file.content_type == mime_type:
                    return True
            except AttributeError:
                pass
        return False

    def save(self, *args, **kwargs):
        if not self.id:
            self.uploaded_at = timezone.now()
        return super(ProjectFile, self).save(*args, **kwargs)


class FavoriteProject(models.Model):
    user = models.ForeignKey(MidUser,
                             related_name="favorites",
                             on_delete=models.CASCADE,
                             db_index=True)
    project = models.ForeignKey(Project,
                                related_name="favorites",
                                on_delete=models.CASCADE,
                                db_index=True)

app/forms.py
from urllib.request import urlretrieve

from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import TemporaryUploadedFile
from django.forms import ModelForm
from django.utils import timezone

from app.enums import VALID_AUDIO_FILE_TYPES, ProjectFileTypeChoices, \
    ProjectKeyChoices
from app.models import MidUser, Project, ProjectFile


class UserForm(UserCreationForm):
    description = forms.CharField(widget=forms.Textarea,
                                  label="Quelques mots sur vous",
                                  required=False)

    class Meta:
        model = MidUser
        field_classes = {'username': UsernameField}
        fields = ("username", "first_name", "last_name", "email", "password1",
                  "password2", "description")

    def is_valid(self):
        return super(UserForm, self).is_valid()

    def save(self, commit=True):
        user = super(UserForm, self).save(commit)
        file_name = "{}.svg".format(user.username)
        url = "https://avatars.dicebear.com/api/croodles-neutral/{}".format(
            file_name
        )
        profile_pic_response = urlretrieve(url)
        profile_pic = open(profile_pic_response[0])
        self.instance.picture.save(file_name, profile_pic)
        return user


class ProjectCreateForm(ModelForm):
    class Meta:
        model = Project
        fields = (
            "name", "audio_file", "key", "tempo", "is_private", "description")

    name = forms.CharField(label="Nom du projet")
    audio_file = forms.FileField(label="Fichier audio")
    description = forms.CharField(widget=forms.Textarea,
                                  label="Description",
                                  required=False)
    key = forms.ChoiceField(choices=ProjectKeyChoices.choices,
                            label="Tonalité")
    is_private = forms.BooleanField(label="Privé", required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(ProjectCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        audio_file = self.cleaned_data.get("audio_file")
        project = Project.objects.create(name=self.cleaned_data.get("name"),
                                         creator=self.user,
                                         description=self.cleaned_data.get(
                                             "description"),
                                         created_at=timezone.now())
        ProjectFile.objects.create(name=audio_file._name,
                                   file=audio_file,
                                   uploaded_at=timezone.now(),
                                   project_file_type=ProjectFileTypeChoices.AUDIO_FILE.name,
                                   project=project)
        return Project

    def is_valid(self):
        is_valid = super(ProjectCreateForm, self).is_valid()
        audio_file = self.cleaned_data.get("audio_file")
        if not audio_file or not self.is_valid_audio_file(audio_file):
            self.add_error("audio_file", ValidationError(
                "Vous devez choisir un fichier audio"))
            is_valid = False
        return is_valid

    @staticmethod
    def is_valid_audio_file(file: TemporaryUploadedFile) -> bool:
        for file_type, mime_type in VALID_AUDIO_FILE_TYPES.items():
            try:
                if file.content_type == mime_type:
                    return True
            except AttributeError:
                pass
        return False


class ProjectUpdateForm(ModelForm):
    class Meta:
        model = Project
        fields = (
            "name", "audio_file", "is_private", "key", "tempo", "description")

    name = forms.CharField(label="Nom du projet")
    audio_file = forms.FileField(label="Fichier audio", required=False)
    description = forms.CharField(widget=forms.Textarea,
                                  label="Description",
                                  required=False)
    is_private = forms.BooleanField(label="Privé", required=False)
    key = forms.ChoiceField(choices=ProjectKeyChoices.choices,
                            label="Tonalité",
                            required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(ProjectUpdateForm, self).__init__(*args, **kwargs)

    def is_valid(self):
        is_valid = super(ProjectUpdateForm, self).is_valid()
        audio_file = self.cleaned_data.get("audio_file")
        if audio_file and not ProjectCreateForm.is_valid_audio_file(
                audio_file
        ):
            self.add_error(
                "audio_file",
                ValidationError("Vous devez choisir un fichier audio")
            )
            is_valid = False
        return is_valid

    def save(self, commit=True):
        project = super(ProjectUpdateForm, self).save(commit)
        audio_file = self.cleaned_data.get("audio_file")
        if audio_file:
            ProjectFile.objects.update_or_create(
                project_file_type=ProjectFileTypeChoices.AUDIO_FILE.name,
                project=project,
                defaults={
                    "file": audio_file,
                    "name": audio_file._name,
                    "uploaded_at": timezone.now()
                }
            )
        return project

app/templates/app/pages/index.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
    <section class="landing-page white-text"
             style="background: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), url('{% static "images/bg2.jpg" %}');margin-bottom: -50px">
        <div class="main-title">
            <p class="center-align" id="main-sentence">
                En manque d'inspiration?
            </p>
            <p class="center-align container">
                Music Ids vous permet de partager, découvrir et contribuer à des créations musicales
            </p>
        </div>
    </section>
{% endblock %}

app/templates/app/pages/my_project_list.html
{% extends "app/base.html" %}
{% load utils %}
{% block content %}
    <section class="main container project-list">
        <ul class="collection">
            {% for project in projects %}
                <li class="collection-item avatar">
                    <a href="#">
                        <img src="/media/{{ project.creator.picture }}"
                             alt="Photo du profil"
                             class="circle profile-picture-project">
                    </a>
                    <span class="title project_title">
                        {{ project.name }}
                    </span>
                    {% if project.is_private %}
                        <span class="orange-text"> (Privé)</span>
                    {% endif %}
                    <div class="row" style="margin-bottom: 0">
                        <div class="col s12">
                            Tonalité: {{ project.key }}
                        </div>
                        <div class="col s12">
                            Tempo: {{ project.tempo }}
                        </div>
                        <div class="col s12">
                            Créé le: {{ project.created_at|date:"d/m/Y" }}
                        </div>
                    </div>
                    {% is_favorite user project as is_fav %}
                    <span class="secondary-content fav-count right">
                        {{ project.favorite_count }}
                    </span>
                    <a href="{% url "ideas-favorite" slug=project.slug %}"
                       class="secondary-content fav">
                        <i class="material-icons {% if is_fav %}fav-star-in{% else %}fav-star-out{% endif %}">
                            grade
                        </i>
                    </a>
                    <a href="{% url "ideas-detail" project.slug %}"
                       class="secondary-content" style="top:75px">
                        Voir le projet
                    </a>
                </li>
            {% endfor %}
        </ul>
    </section>
    {% if is_paginated %}
        <ul class="pagination center">
            {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <i class="material-icons">chevron_left</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#">
                        <i class="material-icons">chevron_left</i>
                    </a>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active">
                        <a href="#">{{ i }}</a>
                    </li>
                {% else %}
                    <li class="waves-effect">
                        <a href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}">
                        <i class="material-icons">chevron_right</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#">
                        <i class="material-icons">chevron_right</i>
                    </a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

app/templates/app/pages/project_create.html
{% extends "app/base.html" %}
{% load materializecss %}
{% block content %}
    <section class="main container main-form">
        <div class="card">
            <div class="card-content center ">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button class="new_name btn tooltipped btn-floating btn-small orange right"
                            style="position: absolute; right: 3vw"
                            data-position="bottom"
                            data-tooltip="Générer un nom au hasard">
                        <i class="material-icons">sync</i>
                    </button>

                    {{ form.name|materializecss }}
                    {{ form.audio_file|materializecss }}
                    {{ form.key|materializecss }}
                    {{ form.tempo|materializecss }}
                    {{ form.description|materializecss }}
                    {{ form.is_private|materializecss }}
                    <br>
                    <div class="col m12">
                        <button class="btn">Créer</button>
                    </div>

                </form>
            </div>
        </div>
    </section>
    {% block js %}
        <script>
            let button = document.querySelector(".new_name")
            let name_field = document.querySelector("#id_name")
            button.addEventListener("click", (event) => {
                event.preventDefault();
                let oReq = new XMLHttpRequest();
                oReq.onload = reqListener;
                oReq.open("get", "{% url "random-project-name" %}", true);
                oReq.send();
            })

            function reqListener() {
                let response = JSON.parse(this.responseText)
                name_field.focus()
                name_field.value = response["name"]
            }

            document.addEventListener('DOMContentLoaded', function () {
                let elems = document.querySelectorAll('select');
                M.FormSelect.init(elems);
            });


        </script>
    {% endblock %}
{% endblock %}

app/templates/app/pages/project_detail.html
{% extends "app/base.html" %}
{% load utils %}
{% load static %}
{% block content %}
    <div class="container main-panel">
        <div class="card">
            <div class="card-content">
                <span class="card-title center">{{ project.name }}
                    {% if project.is_private %}
                        <span class="orange-text private-tag">&nbsp;(Privé)</span>
                    {% endif %}
                    <span class="right" style="font-size: small">
                        {% if is_author %}
                            <a href="{% url "ideas-update" slug=project.slug %}">Modifier</a>
                        {% endif %}
                        {% is_favorite user project as is_fav %}
                        <span class="secondary-content fav-count right">
                                {{ project.favorite_count }}&nbsp;
                        </span>
                        <a href="{% url "ideas-favorite" slug=project.slug %}"
                           class="secondary-content fav">
                            <i class="material-icons {% if is_fav %}fav-star-in{% else %}fav-star-out{% endif %}">
                                grade
                            </i>
                        </a>
                    </span>
                </span><br>
                <p>Créé le: {{ project.created_at|date:"d/m/Y" }} par
                    <a href="{% url "user-detail" pk=project.creator.id %}">
                    {{ project.creator.username }}
                </a>
                </p>
                <p>Dernière
                    modification: {{ project.modified_at|date:"d/m/Y" }}</p>
            </div>
            <div class="card-tabs">
                <ul class="tabs tabs-fixed-width">
                    <li class="tab">
                        <a class="active" href="#audio-file">Fichier audio</a>
                    </li>
                    <li class="tab">
                        <a href="#comments">Commentaires</a>
                    </li>
                </ul>
            </div>
            <div class="card-content grey lighten-4">
                <div id="audio-file">
                    <div class="center row" id="waveform"
                         style="position: relative">
                    </div>
                    <div class="center row">
                        <button class="btn play-pause-button"
                                onclick="wavesurfer.playPause()">
                            <i class="material-icons audio-button-icon">
                                play_circle_filled
                            </i>
                        </button>
                    </div>
                    <div class="center">
                        <a class="btn"
                           href="{% url "download-audio-file" slug=project.slug %}"
                           download="">Télécharger</a>
                    </div>
                    <div class="white description-container">
                        <h5>Description</h5>
                        <p>Tonalité: {{ project.key }}</p>
                        <p>Tempo: {{ project.tempo }}</p>
                        <br>
                        <p>{% if project.description %}
                            {{ project.description|linebreaks }}
                        {% else %}
                            <span>Aucune description</span>
                        {% endif %}
                        </p>
                    </div>
                </div>
                <div id="comments">
                    <div class="center">
                        <p>Fonctionnalité à venir...</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block js %}
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                let el = document.querySelectorAll('.tabs');
                M.Tabs.init(el);
            });
            let wavesurfer = WaveSurfer.create({
                container: '#waveform',
                waveColor: '#a9a9a9',
                progressColor: '#4f4f4f',
                showTime: true,
                opacity: 1,
                backgroundColor: 'white',
                plugins: [
                    WaveSurfer.cursor.create({
                        showTime: true,
                        opacity: 1,
                        customShowTimeStyle: {
                            'background-color': '#000',
                            color: '#fff',
                            padding: '2px',
                            'font-size': '10px'
                        }
                    })
                ]
            });
            wavesurfer.load('/media/{{ project.joined_files.AUDIO_FILE.file }}');
        </script>
        <script src="{% static "js/playpause.js" %}"></script>
    {% endblock %}
{% endblock %}

app/templates/app/pages/project_list.html
{% extends "app/base.html" %}
{% load utils %}
{% block content %}
    <section class="main container project-list">
        <ul class="collection">
            {% for project in projects %}
                {% if not project.is_private %}
                    <li class="collection-item avatar">
                        <a href="{% url "user-detail" pk=project.creator.id %}">
                            <img src="/media/{{ project.creator.picture }}"
                                 alt="Photo du profil"
                                 class="circle profile-picture-project">
                        </a>
                        <span class="title project_title">
                            {{ project.name|title }}
                        </span>
                        <div class="row" style="margin-bottom: 0">
                            <div class="col s12">
                                Tonalité: {{ project.key }}
                            </div>
                            <div class="col s12">
                                Tempo: {{ project.tempo }}
                            </div>
                            <div class="col s12">
                                Créé le: {{ project.created_at|date:"d/m/Y" }}
                            </div>
                        </div>
                        {% is_favorite user project as is_fav %}
                        <span class="secondary-content fav-count right">
                            {{ project.favorite_count }}
                    </span>
                        <a href="{% url "ideas-favorite" slug=project.slug %}"
                           class="secondary-content fav">
                            <i class="material-icons {% if is_fav %}fav-star-in{% else %}fav-star-out{% endif %}">
                                grade
                            </i>
                        </a>
                        <a href="{% url "ideas-detail" project.slug %}"
                           class="secondary-content" style="top:75px">
                            Voir le projet
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </section>
    {% if is_paginated %}
        <ul class="pagination center">
            {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <i class="material-icons">chevron_left</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#">
                        <i class="material-icons">chevron_left</i>
                    </a>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active">
                        <a href="#">{{ i }}</a>
                    </li>
                {% else %}
                    <li class="waves-effect">
                        <a href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}">
                        <i class="material-icons">chevron_right</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#">
                        <i class="material-icons">chevron_right</i>
                    </a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

app/templates/app/pages/user_create.html
{% extends "app/base.html" %}
{% load materializecss %}
{% block content %}
    <section class="main container main-form">
        <div class="card">
            <div class="card-content center">
                <form method="POST">
                    {% csrf_token %}
                    <div class="input-field col s6">
                        <input id="id_username"
                               name="{{ form.username.name }}"
                               type="text"
                               {% if form.username.value != None %}value="{{ form.username.value|stringformat:'s' }}"{% endif %}
                               class="validate {% if form.username.errors %}invalid{% endif %}">
                        <label for="id_username">Nom d'utilisateur</label>
                        <span class="helper-text"
                              data-error="{{ form.username.errors.0 }}"></span>
                    </div>
                    <div class="input-field col s6">
                        <input id="id_first_name"
                               name="{{ form.first_name.name }}"
                               type="text"
                               {% if form.first_name.value != None %}value="{{ form.first_name.value|stringformat:'s' }}"{% endif %}
                               class="validate {% if form.first_name.errors %}invalid{% endif %}">
                        <label for="id_first_name">{{ form.first_name.label }}</label>
                        <span class="helper-text"
                              data-error="{{ form.first_name.errors.0 }}"></span>
                    </div>
                    <div class="input-field col s6">
                        <input id="id_last_name"
                               name="{{ form.last_name.name }}"
                               type="text"
                               {% if form.last_name.value != None %}value="{{ form.last_name.value|stringformat:'s' }}"{% endif %}
                               class="validate {% if form.last_name.errors %}invalid{% endif %}">
                        <label for="id_last_name">{{ form.last_name.label }}</label>
                        <span class="helper-text"
                              data-error="{{ form.last_name.errors.0 }}"></span>
                    </div>
                    <div class="input-field col s6">
                        <input id="id_email"
                               name="{{ form.email.name }}"
                               type="email"
                               {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}"{% endif %}
                               class="validate {% if form.email.errors %}invalid{% endif %}">
                        <label for="id_email">{{ form.email.label }}</label>
                        <span class="helper-text"
                              data-error="{{ form.email.errors.0 }}"></span>
                    </div>
                    <div class="input-field col s6">
                        <input id="id_password1"
                               name="{{ form.password1.name }}"
                               type="password"
                               class="validate {% if form.password1.errors %}invalid{% endif %}">
                        <label for="id_password1">{{ form.password1.label }}</label>
                        <span class="helper-text"
                              data-error="{{ form.password1.errors.0 }}"></span>
                    </div>
                    <div class="input-field col s6">
                        <input id="id_password2"
                               name="{{ form.password2.name }}"
                               type="password"
                               class="validate {% if form.password2.errors %}invalid{% endif %}">
                        <label for="id_password2">{{ form.password2.label }}</label>
                        <span class="helper-text"
                              data-error="{{ form.password2.errors.0 }}"></span>
                    </div>
                    {{ form.description|materializecss }}
                    <button class="btn">Créer un compte</button>
                </form>

            </div>
        </div>
    </section>
{% endblock %}